import Head from 'next/head'
import { Inter } from 'next/font/google'

import Header from '../components/header/Header';
import Main from '../components/main/Main';
import { Footer } from '../components/footer/Footer';
import { useRef } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const skillRef = useRef<any>();
    const workRef = useRef<any>();
    const aboutRef = useRef<any>();
    const homeRef = useRef<any>();


    const scrollToSection = (section: string) => {
        if (section === 'skill') {
            skillRef.current.scrollIntoView({ behavior: 'smooth' });
        } else if (section === 'portfolio') {
            workRef.current.scrollIntoView({ behavior: 'smooth' });
        } else if (section === 'about me') {
            aboutRef.current.scrollIntoView({ behavior: 'smooth' });
        }
        else if (section === 'home') {
            homeRef.current.scrollIntoView({ behavior: 'smooth' });
        }
    };

    return (
        <>
            <Head>
                <title>Mk</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Header onScrollToSection={scrollToSection} homeRef={homeRef} />
            <Main onScrollToSection={scrollToSection} skillRef={skillRef} workRef={workRef} aboutRef={aboutRef} />
            <Footer />
        </>
    )
}