import Head from 'next/head'
import { Inter } from 'next/font/google'

import Header from '../components/header/Header';
import Main from '../components/main/Main';
import { Footer } from '../components/footer/Footer';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Mk</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Header />
            <Main />
            <Footer />
        </>
    )
}
