import Head from 'next/head';
import { Inter } from 'next/font/google'

import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import Header from '@/components/header/Header';
import Main from '@/components/main/Main';
import { Footer } from '@/components/footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export interface HomeProps {
    skillRef: any;
    workRef: any
    aboutRef: any;
    contactRef: any;
    locale?: string;
    onScrollToSection: (section: string) => void;
}

export default function Home(props: HomeProps) {
    const {
        locale,
        aboutRef,
        contactRef,
        skillRef,
        workRef,
        onScrollToSection
    } = props;

    return (
        <>
            <Head>
                <title>Mk</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Main
                onScrollToSection={onScrollToSection}
                skillRef={skillRef}
                workRef={workRef}
                aboutRef={aboutRef}
                contactRef={contactRef}
                locale={locale}
            />
        </>
    )
}

export const getServerSideProps = async (context: any) => {
    const { locale } = context;
    return {
        props: {
            ...(await serverSideTranslations(locale, ['common'])),
            locale,
        },
    };
};